= Technical writing at {company}
:author: Andreas Böttcher
:email: andreas.boettcher@peopleware.com
:docdate:
:company: Peopleware
:product: Peopleware WFM
:docs-product: Help Center

== Introduction

Tech Writing at {company} currently encompasses, among other things, the following tasks:

* Create, review, maintain and update end-user documentation for the {product} product suite
* Create, review, maintain and update translations from English for the following text types into 5 target languages:
** Help Center articles
** UI strings
** Marketing material
** Customer communication material
* Maintain authoring guidelines and style guides
* Manage and maintain Jekyll SSG

In this document, I will outline why I think the processes and tools we currently use to serve these tasks are no longer up to the task, affecting our readiness to provide timely, high-quality documentation and translations.
I will outline an ecosystem of tools and the respective processes to tackle this.
The goal is to achieve a state where the Technical Writing department can fulfill all their tasks efficiently, with high quality and at scale.

[NOTE]
====
I'll refer to the Technical Writing team simply as the *docs team* in the rest of this document.
====

== Status Quo

==== Tech stack

The Technical Writing tech stack is currently made up of the following tools:

* Git/Github (Version Control, Issue Tracking, Reviews)
* Jekyll (Static Site Generator)
* Customized Markdown (Markup and Formatting)
* Github actions/Jenkins/AWS S3 (Build/Deployment/Hosting)
* Customized Lunr (Help Center Search)
* Prettier (Markdown Linter)
* Google Analytics (Analytics)
* Any editor or IDE with a personal choice of plugins

The translation tech stack looks as follows:

* Git/Github (Version Control, Issue Tracking, Reviews, Automation)
* A collection of scripts and interfaces that:
** Triggers the translation process
** Identifies translation units in our customized Markdown
** Searches for target language equivalents for translation units in translation memory +(TM)+ files
** Strips all markup from source language files
** Sends remaining translation units to DeepL and ChatGPT for translation
** Re-inserts all markup from source language files
** Performs segment alignment for source and target language articles
** Extracts source and target language text segments from these articles
** Saves bilingual segment pairs in corresponding translation memory (TM) files
** Detects conflicting/duplicate target language strings per locale for a given source text string

=== Processes

Documentation and translation tasks usually emerge in one of the following ways:

* Informal communication, such as Slack messages, e.g. by support, devs or PMs
* Mentions in issues (mainly from injixo repo)
* Active monitoring of cycle project boards for docs-relevant enhancements
* PRs created by non tech writing staff
* PRs created by automated process steps
* Invites to closing meetings
//TODO how else?

Tasks that are recorded in a Github issue are tracked on a dedicated tech writing board.
Changes and requests only available as PRs are not tracked on the board. For bigger tasks, we try to create an accompanying issue in the help-center repo.

== Challenges and Pain Points

=== Documentation

include::pain-markdown.adoc[leveloffset=+3]
include::pain-repo-bloat.adoc[leveloffset=+3]
include::pain-project-management.adoc[leveloffset=+3]

