= Technical writing at {company}
:author: Andreas Böttcher
:email: andreas.boettcher@peopleware.com
:docdate:
:company: Peopleware
:product: Peopleware WFM
:docs-product: Help Center

== Introduction

Tech Writing at {company} currently encompasses, among other things, the following tasks:

* Create, review, maintain and update end-user documentation for the {product} product suite
* Create, review, maintain and update translations from English for the following text types into 5 target languages:
** Help Center articles
** UI strings
** Marketing material
** Customer communication material
* Maintain authoring guidelines and style guides
* Manage and maintain Jekyll SSG

In this document, I will outline why I think the processes and tools we currently use to serve these tasks are no longer up to the task, affecting our readiness to provide timely, high-quality documentation and translations.
I will outline an ecosystem of tools and the respective processes to tackle this.
The goal is to achieve a state where the Technical Writing department can fulfill all their tasks efficiently, with high quality and at scale.

[NOTE]
====
I'll refer to the Technical Writing team simply as the *docs team* in the rest of this document.
====

== Status Quo

==== Tech stack

The Technical Writing tech stack is currently made up of the following tools:

* Git/Github (Version Control, Issue Tracking, Reviews)
* Jekyll (Static Site Generator)
* Customized Markdown (Markup and Formatting)
* Github actions/Jenkins/AWS S3 (Build/Deployment/Hosting)
* Customized Lunr (Help Center Search)
* Prettier (Markdown Linter)
* Google Analytics (Analytics)
* Any editor or IDE with a personal choice of plugins

The translation tech stack looks as follows:

* Git/Github (Version Control, Issue Tracking, Reviews, Automation)
* A collection of scripts and interfaces that:
** Triggers the translation process
** Identifies translation units in our customized Markdown
** Searches for target language equivalents for translation units in translation memory +(TM)+ files
** Strips all markup from source language files
** Sends remaining translation units to DeepL and ChatGPT for translation
** Re-inserts all markup from source language files
** Performs segment alignment for source and target language articles
** Extracts source and target language text segments from these articles
** Saves bilingual segment pairs in corresponding translation memory (TM) files
** Detects conflicting/duplicate target language strings per locale for a given source text string

=== Processes

Documentation and translation tasks usually emerge in one of the following ways:

* Informal communication, such as Slack messages, e.g. by support, devs or PMs
* Mentions in issues (mainly from injixo repo)
* Active monitoring of cycle project boards for docs-relevant enhancements
* PRs created by non tech writing staff
* PRs created by automated process steps
* Invites to closing meetings
//TODO how else?

Tasks that are recorded in a Github issue are tracked on a dedicated tech writing board.
Changes and requests only available as PRs are not tracked on the board. For bigger tasks, we try to create an accompanying issue in the help-center repo.

== Challenges and Pain Points

=== Documentation

==== Markdown

The fundamental appeal of Markdown lies in its simplicity and ubiquity:
It's everywhere, it's easy to learn and newcomers can get to writing right away--at least in theory.
However, Markdown has a number of drawbacks, especially for large-scale, complex projects like Help Center.

===== Flavors and customization
Markdown comes in upwards of 15 flavors, negating much of its touted simplicity.
While many Markdown features are shared across flavors on a superficial level, they may differ when it comes to the details.
For example, while tables are generally supported, more sophisticated table features such as cell content alignment, captions, row and column spanning may or may not be supported based on the flavor.

Having not _one_ but many Markdown flavors complicates tasks such as:

* Migrating content
* Reusing content
* Creating and managing docs variants
* Applying structured formatting
* Establishing automated content processing
* Implementing and maintaining complex elements (diagrams, math, metadata)

At Peopleware, we use Github Flavored Markdown, which we customized further to meet our requirements and the requirements of our site generator Jekyll.
Examples for these customizations are:

* Section anchors
* Link tags
* CSS role tags
** `.label`
** `.button`
** `.breadcrumbs`
** `.id-label`
** `.menu-item`
* Image tags
* Icon tags
* `<div>` wrappers

.Some Markdown customization used in Help Center
[%collapsible]
====
include::examples/md-customization.adoc[]
====

Committing to one flavor and customizing it also carries the danger of generating a lock-in effect.
Upstream and downstream processes and tools are tailored to meet the requirements of that particular Markdown implementation, making it harder to exchange individual components of the process or tool landscape.

.Migration effort
====
Switching from Jekyll to another static-site generator (SSG) requires migrating the Jekyll-optimized Markdown content to a language or Markdown flavor supported by the new SSG.
Migration tools such as Pandoc can convert from and to well-defined formats out-of-the-box or with little configuration overhead. Such tools would however require extensive configuration and readjustment for customized Markdown.
====

===== Tables

Handling more than the most basic tables in Markdown is essentially impossible without employing additional tools to handle formatting.
//TODO continue here, explain further why md tables suck: PITA to set up, no sophisticated formatting support



















[%header, cols="3,3,3"]
|===
| Feature
| Markdown
| AsciiDoc


|
|
|

|
|
|===





== Translation

=== Tech stack

=== Processes

Despite efforts to automate the translation process, translation still takes up an undue amount of tech writing capacity.
This will eventually impact our readiness to create timely, high-quality end-user documentation.
Translation process automation is an indispensable part of any modern translation workflow.
This includes both process step automation as well as employing neural machine translation and LLM capabilities.
Making the most of these capabilities requires careful planning, proper translation data management and robust language QA.
In this document I explain why I think the current localisation approach is flawed, not future-proof and uneconomical in the long run.

I think our current translation strategy will not yield the desired results and that process and tool adjustments are necessary to ensure tech writing capacity is
Challenges and Pain Points

=== Challenges and Pain Points

I don't think it will be possible to omit post-editing from our l10n workflows for the foreseeable future.
Let me explain why:
...

// ridiculous "overhead-to-actual-translation-work" ratio. we fuck around with translation PRs, TM-generation PRs, what is basically MANUAL file AND line AND string matching in github for these PRs for every documentation PR, no matter how small. this is ridiculous. We spend 5 times more on tracking, reviewing, fixing, approving and aligning about the PRs than we would doing actual translation work. Just fixing a fucking typo somewhere currently generates 11 (!!!!) PRs, all of which need to be reviewed and fixed manually.







As company strongly tied to international markets, InVision needs robust internationalization (i18n) and localization (l10n) strategies to ensure content is delivered in all relevant locales:
On time
With the required quality
Cost-efficiently
To that end, a new localization strategy was started mid-2024. The goal of that strategy is to achieve fully automate the translation process






NOTES:

* TM granularity: reduce segment size to reduce effects of changes in source material to target (ex: adding a comma triggers retranslation of a full paragraph)

* Missing from the tech writing tech stack:
** Authoring support:
*** Spell checker
*** Grammar checker
*** Prose linter
*** On-the-fly link checker
*** Auto-complete

* Generally, tasks for modern translation workflows have “shifted left”. MT/LLM can support linguists in the actual translation generation phase, which allows them to focus more on data tasks such as ensuring clean TMs, meta data application, process improvement etc

* The whole tool stack and process setup is


