= Repo bloat

The Help Center Repo is an amalgaman of UI files, HTML templates and includes, configuration files, markdown documentation content, support scripts for various contexts and localization tooling.

That has a number of drawbacks.

* Responsibilities for the different content types are unclear
* Permission management is more complex
* Navigating the repo and finding content is harder
* Maintenance is harder for one big repo compared to dedicated repos for content, config and UI
* Commit history is cluttered
* CI/CD workflows are slowed down
+
====
Fixed a comma somewhere and just wanna quickly merge the PR, but someone changed a color in a CSS file, added a Code owner or merged one of the gazillion localization PRs in the meantime? Tough luck, you have to merge the change from main into your already approved PR, wait 10+ mins for the automatically triggered build to finish and try again...
====

Long story short: Managing content, presentation and config in a single repo increases complexity and reduces scalability.




















[%header, cols="3,3,3"]
|===
| Feature
| Markdown
| AsciiDoc


|
|
|

|
|
|===





== Translation

=== Processes

Despite efforts to automate the translation process, translation still takes up an undue amount of tech writing capacity.
This will eventually impact our readiness to create timely, high-quality end-user documentation.
Translation process automation is an indispensable part of any modern translation workflow.
This includes both process step automation as well as employing neural machine translation and LLM capabilities.
Making the most of these capabilities requires careful planning, proper translation data management and robust language QA.
In this document I explain why I think the current localisation approach is flawed, not future-proof and uneconomical in the long run.

I think our current translation strategy will not yield the desired results and that process and tool adjustments are necessary to ensure tech writing capacity is
Challenges and Pain Points

=== Challenges and Pain Points

I don't think it will be possible to omit post-editing from our l10n workflows for the foreseeable future.
Let me explain why:
...

// ridiculous "overhead-to-actual-translation-work" ratio. we fuck around with translation PRs, TM-generation PRs, what is basically MANUAL file AND line AND string matching in github for these PRs for every documentation PR, no matter how small. this is ridiculous. We spend 5 times more on tracking, reviewing, fixing, approving and aligning about the PRs than we would doing actual translation work. Just fixing a fucking typo somewhere currently generates 11 (!!!!) PRs, all of which need to be reviewed and fixed manually.







As company strongly tied to international markets, InVision needs robust internationalization (i18n) and localization (l10n) strategies to ensure content is delivered in all relevant locales:
On time
With the required quality
Cost-efficiently
To that end, a new localization strategy was started mid-2024. The goal of that strategy is to achieve fully automate the translation process






NOTES:

* TM granularity: reduce segment size to reduce effects of changes in source material to target (ex: adding a comma triggers retranslation of a full paragraph)

* Missing from the tech writing tech stack:
** Authoring support:
*** Spell checker
*** Grammar checker
*** Prose linter
*** On-the-fly link checker
*** Auto-complete

* Generally, tasks for modern translation workflows have “shifted left”. MT/LLM can support linguists in the actual translation generation phase, which allows them to focus more on data tasks such as ensuring clean TMs, meta data application, process improvement etc

* The whole tool stack and process setup is