= Repo bloat

The Help Center Repo is an amalgaman of UI files, HTML templates and includes, configuration files, markdown documentation content, support scripts for various contexts and localization tooling.

That has a number of drawbacks.

* Responsibilities for the different content types are unclear
* Permission management is more complex
* Navigating the repo and finding content is harder
* Maintenance is harder for one big repo compared to dedicated repos for content, config and UI
* Commit history is cluttered
* CI/CD workflows are slowed down
+
====
Fixed a comma somewhere and just wanna quickly merge the PR, but someone changed a color in a CSS file, added a Code owner or merged one of the gazillion localization PRs in the meantime? Tough luck, you have to merge the change from main into your already approved PR, wait 10+ mins for the automatically triggered build to finish and try again...
====

Long story short: Managing content, presentation and config in a single repo increases complexity and reduces scalability.




















